iplist:
  boot:
    admin:
      ip: admin.sinnake.kro.kr
      port: 9090
  eureka:
    defaultZone:
      ip: eureka.sinnake.kro.kr
      port: 8761
      
server:
  address: s1nnak2.iptime.org
  port: 8761
  tomcat:
    max-connections: 15000
    min-spare-threads: 200
    max-threads: 500
        
spring:
  jackson:
    serialization:            
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false  
  application:
    name: eurekaServer
  boot:
    admin:
      client:      
        url:
        - http://${iplist.boot.admin.ip}:${iplist.boot.admin.port}

eureka:
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.1
  instance:
    hostname: ${iplist.eureka.defaultZone.ip}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

logging:
  file: ./logs/eureka/eurekaServerLogFile.txt