iplist:
  boot:
    admin:
      ip: 192.168.0.40
      port: 9090
  eureka:
    defaultZone:
      ip: 192.168.0.45
      port: 8761
      
server:
  port: 8761
  tomcat:
    max-connections: 15000
    min-spare-threads: 200
    max-threads: 500
        
spring:
  jackson:
    serialization:            
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false  
  application:
    name: eurekaServer
  boot:
    admin:
      client:
        instance:
          prefer-ip: true      
        url:
        - http://${iplist.boot.admin.ip}:${iplist.boot.admin.port}

eureka:
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.1
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

logging:
  file: ./logs/eureka/eurekaServerLogFile.txt