server:
  port: 7000
  tomcat:
    max-connections: 15000
    
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:            
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
  application:
    name: zuul-service
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url:
        - http://192.168.0.40:9090  
  session:
    timeout:
      seconds: 1800
    store-type: REDIS
    redis:
      flush-mode: on-save
      namespace: spring:session
      cleanup-cron : 0 0 5 31 2 ?      
  redis:
    host: 192.168.0.40
    port: 6379
    password: sinnake

zuul:
  ribbon-isolation-strategy: THREAD
  thread-pool:
    use-separate-thread-pools: true
  host:
    max-total-connections: 1000
    max-per-route-connections: 400
  ignored-services: '*'
  sensitive-headers:  
  routes: 
    member:      
        path: /member/**
        service-id: member
        strip-prefix: false
  
hystrix:
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 2000
      #allowMaximumSizeToDivergeFromCoreSize: true
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
              timeoutInMilliseconds: 100000
eureka:
  instance:
    hostname: localhost
    status-page-url: http://${eureka.instance.hostname}:${server.port}/info
    health-check-url-path: http://${eureka.instance.hostname}:${server.port}/health
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://192.168.0.45:8761/eureka/

member:
  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
    NFLoadBalancerPingInterval: 1
    ConnectTimeout: 10000
    ReadTimeout: 10000
    ServerListRefreshInterval : 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 300
    MaxAutoRetries: 1
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

logging:
  file: ./logs/zuul/zuulLogFile.txt

httppool:
  maxPerRoute: 100
  maxTotal: 1000
  connectionRequestTimeout: 5000
  connectTimeout: 5000
  socketTimeout: 5000
 
tokencontrol:
  token-control: "cookie"