iplist:
  boot:
    admin:
      ip: admin.sinnake.kro.kr
      port: 9090
  eureka:
    defaultZone:
      ip: s1nnak2.iptime.org
      port: 8761

server:
  address: s1nnak2.iptime.org
  port: 8082
  tomcat:
    max-connections: 15000

spring:
  profiles:
    active:
    - local
  jackson:
    serialization:            
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: categories
  boot:
    admin:
      client:
        url:
        - http://${iplist.boot.admin.ip}:${iplist.boot.admin.port}
    
eureka:
  instance:
    hostname: ${server.address}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/info
    health-check-url-path: http://${eureka.instance.hostname}:${server.port}/health
  client: 
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${iplist.eureka.defaultZone.ip}:${iplist.eureka.defaultZone.port}/eureka/

management:
  health:
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
        - "*"

logging:
  file: ./logs/categories/categoriesLogFile.txt
  
httppool:
  maxPerRoute: 100
  maxTotal: 1000
  connectionRequestTimeout: 5000
  connectTimeout: 5000
  socketTimeout: 5000